[target.aarch64-linux-android]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang"

[target.armv7-linux-androideabi]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi28-clang"

[target.i686-linux-android]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android28-clang"
